/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as BrandKitRouteImport } from './routes/brand-kit'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AgencyRouteImport } from './routes/agency'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSegmentsRouteImport } from './routes/admin.segments'
import { Route as AdminOrgsRouteImport } from './routes/admin.orgs'
import { Route as AdminMarginGuardsRouteImport } from './routes/admin.margin-guards'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminHealthRouteImport } from './routes/admin.health'
import { Route as AdminCostRouteImport } from './routes/admin.cost'
import { Route as AdminBuildRouteImport } from './routes/admin.build'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandKitRoute = BrandKitRouteImport.update({
  id: '/brand-kit',
  path: '/brand-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyRoute = AgencyRouteImport.update({
  id: '/agency',
  path: '/agency',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSegmentsRoute = AdminSegmentsRouteImport.update({
  id: '/segments',
  path: '/segments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrgsRoute = AdminOrgsRouteImport.update({
  id: '/orgs',
  path: '/orgs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarginGuardsRoute = AdminMarginGuardsRouteImport.update({
  id: '/margin-guards',
  path: '/margin-guards',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHealthRoute = AdminHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCostRoute = AdminCostRouteImport.update({
  id: '/cost',
  path: '/cost',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBuildRoute = AdminBuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agency': typeof AgencyRoute
  '/analytics': typeof AnalyticsRoute
  '/billing': typeof BillingRoute
  '/brand-kit': typeof BrandKitRoute
  '/clients': typeof ClientsRoute
  '/dashboard': typeof DashboardRoute
  '/editor': typeof EditorRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/onboarding': typeof OnboardingRoute
  '/partner': typeof PartnerRoute
  '/plan': typeof PlanRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/studio': typeof StudioRoute
  '/team': typeof TeamRoute
  '/admin/build': typeof AdminBuildRoute
  '/admin/cost': typeof AdminCostRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/margin-guards': typeof AdminMarginGuardsRoute
  '/admin/orgs': typeof AdminOrgsRoute
  '/admin/segments': typeof AdminSegmentsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agency': typeof AgencyRoute
  '/analytics': typeof AnalyticsRoute
  '/billing': typeof BillingRoute
  '/brand-kit': typeof BrandKitRoute
  '/clients': typeof ClientsRoute
  '/dashboard': typeof DashboardRoute
  '/editor': typeof EditorRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/onboarding': typeof OnboardingRoute
  '/partner': typeof PartnerRoute
  '/plan': typeof PlanRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/studio': typeof StudioRoute
  '/team': typeof TeamRoute
  '/admin/build': typeof AdminBuildRoute
  '/admin/cost': typeof AdminCostRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/margin-guards': typeof AdminMarginGuardsRoute
  '/admin/orgs': typeof AdminOrgsRoute
  '/admin/segments': typeof AdminSegmentsRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agency': typeof AgencyRoute
  '/analytics': typeof AnalyticsRoute
  '/billing': typeof BillingRoute
  '/brand-kit': typeof BrandKitRoute
  '/clients': typeof ClientsRoute
  '/dashboard': typeof DashboardRoute
  '/editor': typeof EditorRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/onboarding': typeof OnboardingRoute
  '/partner': typeof PartnerRoute
  '/plan': typeof PlanRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/studio': typeof StudioRoute
  '/team': typeof TeamRoute
  '/admin/build': typeof AdminBuildRoute
  '/admin/cost': typeof AdminCostRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/margin-guards': typeof AdminMarginGuardsRoute
  '/admin/orgs': typeof AdminOrgsRoute
  '/admin/segments': typeof AdminSegmentsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agency'
    | '/analytics'
    | '/billing'
    | '/brand-kit'
    | '/clients'
    | '/dashboard'
    | '/editor'
    | '/login'
    | '/marketplace'
    | '/onboarding'
    | '/partner'
    | '/plan'
    | '/review'
    | '/settings'
    | '/signup'
    | '/studio'
    | '/team'
    | '/admin/build'
    | '/admin/cost'
    | '/admin/health'
    | '/admin/login'
    | '/admin/margin-guards'
    | '/admin/orgs'
    | '/admin/segments'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agency'
    | '/analytics'
    | '/billing'
    | '/brand-kit'
    | '/clients'
    | '/dashboard'
    | '/editor'
    | '/login'
    | '/marketplace'
    | '/onboarding'
    | '/partner'
    | '/plan'
    | '/review'
    | '/settings'
    | '/signup'
    | '/studio'
    | '/team'
    | '/admin/build'
    | '/admin/cost'
    | '/admin/health'
    | '/admin/login'
    | '/admin/margin-guards'
    | '/admin/orgs'
    | '/admin/segments'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agency'
    | '/analytics'
    | '/billing'
    | '/brand-kit'
    | '/clients'
    | '/dashboard'
    | '/editor'
    | '/login'
    | '/marketplace'
    | '/onboarding'
    | '/partner'
    | '/plan'
    | '/review'
    | '/settings'
    | '/signup'
    | '/studio'
    | '/team'
    | '/admin/build'
    | '/admin/cost'
    | '/admin/health'
    | '/admin/login'
    | '/admin/margin-guards'
    | '/admin/orgs'
    | '/admin/segments'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgencyRoute: typeof AgencyRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BillingRoute: typeof BillingRoute
  BrandKitRoute: typeof BrandKitRoute
  ClientsRoute: typeof ClientsRoute
  DashboardRoute: typeof DashboardRoute
  EditorRoute: typeof EditorRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRoute
  OnboardingRoute: typeof OnboardingRoute
  PartnerRoute: typeof PartnerRoute
  PlanRoute: typeof PlanRoute
  ReviewRoute: typeof ReviewRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  StudioRoute: typeof StudioRoute
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-kit': {
      id: '/brand-kit'
      path: '/brand-kit'
      fullPath: '/brand-kit'
      preLoaderRoute: typeof BrandKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency': {
      id: '/agency'
      path: '/agency'
      fullPath: '/agency'
      preLoaderRoute: typeof AgencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/segments': {
      id: '/admin/segments'
      path: '/segments'
      fullPath: '/admin/segments'
      preLoaderRoute: typeof AdminSegmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orgs': {
      id: '/admin/orgs'
      path: '/orgs'
      fullPath: '/admin/orgs'
      preLoaderRoute: typeof AdminOrgsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/margin-guards': {
      id: '/admin/margin-guards'
      path: '/margin-guards'
      fullPath: '/admin/margin-guards'
      preLoaderRoute: typeof AdminMarginGuardsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/health': {
      id: '/admin/health'
      path: '/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AdminHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cost': {
      id: '/admin/cost'
      path: '/cost'
      fullPath: '/admin/cost'
      preLoaderRoute: typeof AdminCostRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/build': {
      id: '/admin/build'
      path: '/build'
      fullPath: '/admin/build'
      preLoaderRoute: typeof AdminBuildRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBuildRoute: typeof AdminBuildRoute
  AdminCostRoute: typeof AdminCostRoute
  AdminHealthRoute: typeof AdminHealthRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMarginGuardsRoute: typeof AdminMarginGuardsRoute
  AdminOrgsRoute: typeof AdminOrgsRoute
  AdminSegmentsRoute: typeof AdminSegmentsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBuildRoute: AdminBuildRoute,
  AdminCostRoute: AdminCostRoute,
  AdminHealthRoute: AdminHealthRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMarginGuardsRoute: AdminMarginGuardsRoute,
  AdminOrgsRoute: AdminOrgsRoute,
  AdminSegmentsRoute: AdminSegmentsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AgencyRoute: AgencyRoute,
  AnalyticsRoute: AnalyticsRoute,
  BillingRoute: BillingRoute,
  BrandKitRoute: BrandKitRoute,
  ClientsRoute: ClientsRoute,
  DashboardRoute: DashboardRoute,
  EditorRoute: EditorRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRoute,
  OnboardingRoute: OnboardingRoute,
  PartnerRoute: PartnerRoute,
  PlanRoute: PlanRoute,
  ReviewRoute: ReviewRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  StudioRoute: StudioRoute,
  TeamRoute: TeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
