/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as BrandKitRouteImport } from './routes/brand-kit'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AgencyRouteImport } from './routes/agency'
import { Route as IndexRouteImport } from './routes/index'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandKitRoute = BrandKitRouteImport.update({
  id: '/brand-kit',
  path: '/brand-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyRoute = AgencyRouteImport.update({
  id: '/agency',
  path: '/agency',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agency': typeof AgencyRoute
  '/billing': typeof BillingRoute
  '/brand-kit': typeof BrandKitRoute
  '/clients': typeof ClientsRoute
  '/dashboard': typeof DashboardRoute
  '/editor': typeof EditorRoute
  '/marketplace': typeof MarketplaceRoute
  '/onboarding': typeof OnboardingRoute
  '/partner': typeof PartnerRoute
  '/plan': typeof PlanRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/studio': typeof StudioRoute
  '/team': typeof TeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agency': typeof AgencyRoute
  '/billing': typeof BillingRoute
  '/brand-kit': typeof BrandKitRoute
  '/clients': typeof ClientsRoute
  '/dashboard': typeof DashboardRoute
  '/editor': typeof EditorRoute
  '/marketplace': typeof MarketplaceRoute
  '/onboarding': typeof OnboardingRoute
  '/partner': typeof PartnerRoute
  '/plan': typeof PlanRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/studio': typeof StudioRoute
  '/team': typeof TeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agency': typeof AgencyRoute
  '/billing': typeof BillingRoute
  '/brand-kit': typeof BrandKitRoute
  '/clients': typeof ClientsRoute
  '/dashboard': typeof DashboardRoute
  '/editor': typeof EditorRoute
  '/marketplace': typeof MarketplaceRoute
  '/onboarding': typeof OnboardingRoute
  '/partner': typeof PartnerRoute
  '/plan': typeof PlanRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/studio': typeof StudioRoute
  '/team': typeof TeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agency'
    | '/billing'
    | '/brand-kit'
    | '/clients'
    | '/dashboard'
    | '/editor'
    | '/marketplace'
    | '/onboarding'
    | '/partner'
    | '/plan'
    | '/review'
    | '/settings'
    | '/studio'
    | '/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agency'
    | '/billing'
    | '/brand-kit'
    | '/clients'
    | '/dashboard'
    | '/editor'
    | '/marketplace'
    | '/onboarding'
    | '/partner'
    | '/plan'
    | '/review'
    | '/settings'
    | '/studio'
    | '/team'
  id:
    | '__root__'
    | '/'
    | '/agency'
    | '/billing'
    | '/brand-kit'
    | '/clients'
    | '/dashboard'
    | '/editor'
    | '/marketplace'
    | '/onboarding'
    | '/partner'
    | '/plan'
    | '/review'
    | '/settings'
    | '/studio'
    | '/team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgencyRoute: typeof AgencyRoute
  BillingRoute: typeof BillingRoute
  BrandKitRoute: typeof BrandKitRoute
  ClientsRoute: typeof ClientsRoute
  DashboardRoute: typeof DashboardRoute
  EditorRoute: typeof EditorRoute
  MarketplaceRoute: typeof MarketplaceRoute
  OnboardingRoute: typeof OnboardingRoute
  PartnerRoute: typeof PartnerRoute
  PlanRoute: typeof PlanRoute
  ReviewRoute: typeof ReviewRoute
  SettingsRoute: typeof SettingsRoute
  StudioRoute: typeof StudioRoute
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-kit': {
      id: '/brand-kit'
      path: '/brand-kit'
      fullPath: '/brand-kit'
      preLoaderRoute: typeof BrandKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency': {
      id: '/agency'
      path: '/agency'
      fullPath: '/agency'
      preLoaderRoute: typeof AgencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgencyRoute: AgencyRoute,
  BillingRoute: BillingRoute,
  BrandKitRoute: BrandKitRoute,
  ClientsRoute: ClientsRoute,
  DashboardRoute: DashboardRoute,
  EditorRoute: EditorRoute,
  MarketplaceRoute: MarketplaceRoute,
  OnboardingRoute: OnboardingRoute,
  PartnerRoute: PartnerRoute,
  PlanRoute: PlanRoute,
  ReviewRoute: ReviewRoute,
  SettingsRoute: SettingsRoute,
  StudioRoute: StudioRoute,
  TeamRoute: TeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
